import type { IColors } from './types';

export const light: IColors = {
  accent: '#FFD600',
  accentLight: '#FFE033',
  accentDark: '#CCB000',
  accentMuted: '#FFD60026',
  background: '#F5F5F5',
  surface: '#FFFFFF',
  surfaceRaised: '#E5E5EA',
  surfaceOverlay: '#EBEBEB',
  textPrimary: '#0A0A0A',
  textSecondary: '#555555',
  textDisabled: '#AAAAAA',
  textInverse: '#F5F5F5',
  borderSubtle: '#E5E5E5',
  borderDefault: '#D0D0D0',
  borderStrong: '#AAAAAA',
  success: '#16A34A',
  error: '#DC2626',
  warning: '#EA580C',
  info: '#2563EB',
  white: "#FAFAFA",
  black: "#181717",
};
